services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_blacklist
    ports:
      - "3307:3306"
    networks:
      - my-network-fraud
networks:
  my-network-fraud: